# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "CICDTestProj.xcodeproj")
    sync_code_signing(type: "appstore")
    build_app(scheme: "CICDTestProj")
    upload_to_testflight
  end

  # 앱 빌드 실패시 slack으로 메세지 전달
  lane :tests do
  run_tests(scheme: "CICDTestProj",
            slack_url: "https://hooks.slack.com/services/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",
            slack_channel: "#channel")
  end
end
